export const pokemonTypeIcons = {
  water: require('../assets/icons/water.png'),
  fire: require('../assets/icons/fire.png'),
  bug: require('../assets/icons/bug.png'),
  electric: require('../assets/icons/electric.png'),
  grass: require('../assets/icons/grass.png'),
  poison: require('../assets/icons/poison.png'),
  flying: require('../assets/icons/flying.png'),
  normal: require('../assets/icons/normal.png'),
  dark: require('../assets/icons/dark.png'),
  dragon: require('../assets/icons/dragon.png'),
  fairy: require('../assets/icons/fairy.png'),
  fighting: require('../assets/icons/fight.png'),
  ghost: require('../assets/icons/ghost.png'),
  ground: require('../assets/icons/ground.png'),
  ice: require('../assets/icons/ice.png'),
  psychic: require('../assets/icons/psychic.png'),
  rock: require('../assets/icons/rock.png'),
  steel: require('../assets/icons/steel.png'),
};
